/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bestBurger;

/**
 *
 * @author HP
 */
public class BestBurger extends javax.swing.JFrame {

    /**
     * Creates new form BestBurger
     */
    public BestBurger() {
        initComponents();
        setTitle("Best Burger");
        setLocationRelativeTo(null);
        cbxBurger.setVisible(false);
        chkCheese.setVisible(false);
        cbxDrink.setVisible(false);
        cbxDrinkOption.setVisible(false);
        cbxDessert.setVisible(false);
        chkDrink.setEnabled(false);
        chkDessert.setEnabled(false);
        btnNewOrder.setEnabled(false);
        btnCalculate.setEnabled(false);
        lblPrice.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlOptions = new javax.swing.JPanel();
        chkBurger = new javax.swing.JCheckBox();
        chkFrenchFries = new javax.swing.JCheckBox();
        chkDrink = new javax.swing.JCheckBox();
        chkDessert = new javax.swing.JCheckBox();
        cbxBurger = new javax.swing.JComboBox<>();
        chkCheese = new javax.swing.JCheckBox();
        cbxDrink = new javax.swing.JComboBox<>();
        cbxDrinkOption = new javax.swing.JComboBox<>();
        cbxDessert = new javax.swing.JComboBox<>();
        pnlActions = new javax.swing.JPanel();
        btnNewOrder = new javax.swing.JButton();
        btnCalculate = new javax.swing.JButton();
        lblPrice = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlOptions.setBorder(javax.swing.BorderFactory.createTitledBorder("Options"));

        chkBurger.setText("Burger");
        chkBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBurgerActionPerformed(evt);
            }
        });

        chkFrenchFries.setText("French Fries");
        chkFrenchFries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkFrenchFriesActionPerformed(evt);
            }
        });

        chkDrink.setText("Drink");
        chkDrink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDrinkActionPerformed(evt);
            }
        });

        chkDessert.setText("Dessert");
        chkDessert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDessertActionPerformed(evt);
            }
        });

        cbxBurger.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ham", "Chicken", "Fish" }));
        cbxBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxBurgerActionPerformed(evt);
            }
        });

        chkCheese.setText("Cheese");

        cbxDrink.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Beverage", "IceTea" }));
        cbxDrink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDrinkActionPerformed(evt);
            }
        });

        cbxDrinkOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pepsi", "7up" }));

        cbxDessert.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ice Cream", "Donnuts" }));

        javax.swing.GroupLayout pnlOptionsLayout = new javax.swing.GroupLayout(pnlOptions);
        pnlOptions.setLayout(pnlOptionsLayout);
        pnlOptionsLayout.setHorizontalGroup(
            pnlOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkFrenchFries)
                    .addGroup(pnlOptionsLayout.createSequentialGroup()
                        .addComponent(chkDessert)
                        .addGap(18, 18, 18)
                        .addComponent(cbxDessert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlOptionsLayout.createSequentialGroup()
                        .addGroup(pnlOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlOptionsLayout.createSequentialGroup()
                                .addComponent(chkBurger)
                                .addGap(36, 36, 36)
                                .addComponent(cbxBurger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlOptionsLayout.createSequentialGroup()
                                .addComponent(chkDrink)
                                .addGap(30, 30, 30)
                                .addComponent(cbxDrink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(pnlOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxDrinkOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkCheese))))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        pnlOptionsLayout.setVerticalGroup(
            pnlOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkBurger)
                    .addComponent(cbxBurger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkCheese))
                .addGap(18, 18, 18)
                .addComponent(chkFrenchFries)
                .addGap(18, 18, 18)
                .addGroup(pnlOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkDrink)
                    .addComponent(cbxDrink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxDrinkOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(pnlOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkDessert)
                    .addComponent(cbxDessert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlActions.setBorder(javax.swing.BorderFactory.createTitledBorder("Actions"));

        btnNewOrder.setText("New Order");
        btnNewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewOrderActionPerformed(evt);
            }
        });

        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        lblPrice.setText("Price:");

        javax.swing.GroupLayout pnlActionsLayout = new javax.swing.GroupLayout(pnlActions);
        pnlActions.setLayout(pnlActionsLayout);
        pnlActionsLayout.setHorizontalGroup(
            pnlActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlActionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNewOrder)
                .addGap(18, 18, 18)
                .addComponent(btnCalculate)
                .addGap(18, 18, 18)
                .addComponent(lblPrice)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlActionsLayout.setVerticalGroup(
            pnlActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlActionsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewOrder)
                    .addComponent(btnCalculate)
                    .addComponent(lblPrice))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlActions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlActions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBurgerActionPerformed
        if (chkBurger.isSelected()) {
            cbxBurger.setVisible(true);
            chkCheese.setVisible(true);
            chkDrink.setEnabled(true);
            chkDessert.setEnabled(true);
        } else {
            cbxBurger.setVisible(false);
            chkCheese.setVisible(false);
            cbxBurger.setSelectedIndex(0);
            chkCheese.setSelected(false);
            chkDrink.setEnabled(false);
            chkDessert.setEnabled(false);
            chkDrink.setSelected(false);
            chkDessert.setSelected(false);
            cbxDrink.setSelectedIndex(0);
            cbxDrinkOption.setVisible(false);
            cbxDrink.setVisible(false);
            cbxDessert.setVisible(false);
            cbxDessert.setSelectedIndex(0);
        }
        if (chkBurger.isSelected() || chkFrenchFries.isSelected()) {
            btnNewOrder.setEnabled(true);
            btnCalculate.setEnabled(true);
        } else {
            btnNewOrder.setEnabled(false);
            btnCalculate.setEnabled(false);
        }
    }//GEN-LAST:event_chkBurgerActionPerformed

    private void cbxBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxBurgerActionPerformed
        chkCheese.setSelected(false);
        if (cbxBurger.getSelectedItem().equals("Fish")) {
            chkCheese.setEnabled(false);
        } else {
            chkCheese.setEnabled(true);
        }
    }//GEN-LAST:event_cbxBurgerActionPerformed

    private void chkDrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDrinkActionPerformed
        if (chkDrink.isSelected()) {
            cbxDrink.setVisible(true);
            cbxDrinkOption.setVisible(true);
        } else {
            cbxDrink.setSelectedIndex(0);
            cbxDrinkOption.setVisible(false);
            cbxDrink.setVisible(false);
        }
    }//GEN-LAST:event_chkDrinkActionPerformed

    private void cbxDrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDrinkActionPerformed
        cbxDrinkOption.removeAllItems();
        if (cbxDrink.getSelectedItem().equals("Beverage")) {
            cbxDrinkOption.addItem("Pepsi");
            cbxDrinkOption.addItem("7up");
        } else if (cbxDrink.getSelectedItem().equals("IceTea")) {
            cbxDrinkOption.addItem("Lemon");
            cbxDrinkOption.addItem("Peach");
        }
    }//GEN-LAST:event_cbxDrinkActionPerformed

    private void chkDessertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDessertActionPerformed
        if (chkDessert.isSelected()) {
            cbxDessert.setVisible(true);
        } else {
            cbxDessert.setVisible(false);
            cbxDessert.setSelectedIndex(0);
        }
    }//GEN-LAST:event_chkDessertActionPerformed

    private void chkFrenchFriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkFrenchFriesActionPerformed
        if (chkBurger.isSelected() || chkFrenchFries.isSelected()) {
            btnNewOrder.setEnabled(true);
            btnCalculate.setEnabled(true);
        } else {
            btnNewOrder.setEnabled(false);
            btnCalculate.setEnabled(false);
        }
    }//GEN-LAST:event_chkFrenchFriesActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        int price = 0;
        if (chkBurger.isSelected()) {
            switch (cbxBurger.getSelectedItem().toString()) {
                case "Ham":
                    price += 9000;
                    break;
                case "Chicken":
                    price += 8000;
                    break;
                case "Fish":
                    price += 7000;
                    break;
            }
            if (chkCheese.isSelected()) {
                price += 1000;
            }
            if (chkDrink.isSelected()) {
                switch (cbxDrink.getSelectedItem().toString()) {
                    case "Beverage":
                        price += 1000;
                        break;
                    case "IceTea":
                        price += 1500;
                        break;
                }
            }
            if (chkDessert.isSelected()) {
                switch (cbxDessert.getSelectedItem().toString()) {
                    case "Ice Cream":
                        price += 2500;
                        break;
                    case "Donnuts":
                        price += 2000;
                        break;
                }
            }
        }
        if (chkFrenchFries.isSelected()) {
            price += 2500;
        }
        if (chkBurger.isSelected() && chkFrenchFries.isSelected()
                && chkDrink.isSelected()) {
            if (chkDessert.isSelected()) {
                price -= 1500;
            } else {
                price -= 1000;
            }
        }
        lblPrice.setText("Price: " + price + "LL");
        lblPrice.setVisible(true);

        //disable all options components
        chkBurger.setEnabled(false);
        cbxBurger.setEnabled(false);
        chkCheese.setEnabled(false);
        chkFrenchFries.setEnabled(false);
        chkDrink.setEnabled(false);
        cbxDrink.setEnabled(false);
        cbxDrinkOption.setEnabled(false);
        chkDessert.setEnabled(false);
        cbxDessert.setEnabled(false);
        btnCalculate.setEnabled(false);
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnNewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewOrderActionPerformed
        /*
        this.dispose();
        BestBurger bestBurger = new BestBurger();
        bestBurger.setVisible(true);
        */
        chkBurger.setEnabled(true);
        chkBurger.setSelected(false);
        cbxBurger.setEnabled(true);
        cbxBurger.setSelectedIndex(0);
        chkCheese.setEnabled(true);
        chkCheese.setSelected(false);
        chkFrenchFries.setEnabled(true);
        chkFrenchFries.setSelected(false);
        chkDrink.setSelected(false);
        cbxDrink.setSelectedIndex(0);
        cbxDrink.setEnabled(true);
        cbxDrinkOption.setEnabled(true);
        chkDessert.setSelected(false);
        cbxDessert.setSelectedIndex(0);
        cbxDessert.setEnabled(true);
        btnNewOrder.setEnabled(false);
        lblPrice.setVisible(false);
        cbxBurger.setVisible(false);
        chkCheese.setVisible(false);
        cbxDrink.setVisible(false);
        cbxDrinkOption.setVisible(false);
        cbxDessert.setVisible(false);
        chkDrink.setEnabled(false);
        chkDessert.setEnabled(false);
        btnCalculate.setEnabled(false);
    }//GEN-LAST:event_btnNewOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BestBurger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BestBurger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BestBurger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BestBurger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BestBurger().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnNewOrder;
    private javax.swing.JComboBox<String> cbxBurger;
    private javax.swing.JComboBox<String> cbxDessert;
    private javax.swing.JComboBox<String> cbxDrink;
    private javax.swing.JComboBox<String> cbxDrinkOption;
    private javax.swing.JCheckBox chkBurger;
    private javax.swing.JCheckBox chkCheese;
    private javax.swing.JCheckBox chkDessert;
    private javax.swing.JCheckBox chkDrink;
    private javax.swing.JCheckBox chkFrenchFries;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JPanel pnlActions;
    private javax.swing.JPanel pnlOptions;
    // End of variables declaration//GEN-END:variables
}
